$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
database:
  uri: mongodb://user:password@localhost:27017/db?authSource=admin
# Predefined
predefined:
    users:
    - login: admin
      password: admin
      role: admin
      name: Admin
    - login: moderator
      password: moderator
      role: moderator
      name: Moderator
    - login: user
      password: user
      role: user
      name: User
auth:
    # Run 'openssl rand -hex 32' to generate key
    session_secret_key: "secret"
telegram:
    # Get your bot token from @BotFather
    bot_username: YourBotName
    bot_token: YourBotToken
