$schema: "./settings.schema.yaml"
# ---------- Параметры приложения ----- #
environment: production

# Настройки безопасности запросов от браузера
https_only_cookie: false
secure_prefix_cookie: false
wildcard_allow_origin_regex: false

# Параметры подключения к базе данных MongoDB
database:
  uri: mongodb://mongoadmin:secret@localhost:27017/db?authSource=admin

# Предопределенные пользователи для первого запуска
predefined:
    users:
    - login: admin
      password: admin
      role: admin
      name: Admin
    - login: moderator
      password: moderator
      role: moderator
      name: Moderator
    - login: user
      password: user
      role: default
      name: User

# Параметры аутентификации
auth:
    # Запустите 'openssl rand -hex 32' для генерации ключа
    session_secret_key: "secret"

# Подключение Telegram как метода входа в систему
telegram:
    # Создайте бота через @BotFather
    bot_username: YourBotName
    bot_token: YourBotToken
